### ISSUE TITLE
Thanks for letting me know about your project

### ISSUE THREAD

**Issue by bohyn** [ppetrid/yawd-elfinder#1]
Hello,
I've checked it and it looks perfect. I will definitely try to use it. I have a few more tips for improvements:
- I think, that it would be nice to have some support for i18n in jQuery plugin, which you are using to represent an ElfinderField.
- When I was was working on improvements of original django-elfinder, I tried to make it easier to integrate it with TinyMCE editor. This only measns, that I wrote two simple views, one for rendering JavaScript with callback for TinyMCE editor and one simple wrapper for elFinder connector view.

If you want, I can adapt my current TinyMCE-connector code to be used in your new project.

Martin

**Comment by ghost** [comment]
Ok, thanks! I keep this ticket open for the i18n support. yawd-elfinder should be multilingual and we're working on this; I expect to commit the changes in the next few days.

As far as the TinyMCE integration is concerned, I think yawd-elfinder should have a concrete file-management direction, no matter what WYSIWUG editor one uses. That being said, if you're still interested you can provide a snippet in http://djangosnippets.org/ or even write a post about how yawd-elfinder can be used with TinyMCE. We can upload it to a django-related blog for future reference, or even use the yawd blog - http://blog.yawd.eu - (naming you as the author). We use TinyMCE ourserlves, so I think this could be of interest to the community.

**Comment by ghost** [comment]
i18n support was added. It locates the current django language and localizes elfinder appropriately. the update is reflected in the docs as well. bohyn, do you think this issue can close?
