### ISSUE TITLE
Moving File forward and backwards again causes Error. Solution appended

### ISSUE THREAD

**Issue by Phaiax** [ppetrid/yawd-elfinder#15]
Move a file into an other folder and then back into the first without restarting the django server:
The movement fails.

Solution: Clear cached stat not only of the source-folder, but also of the source file:
add 
        self._clear_cached_stat(src)
into
elfinder/volumes/base.py after line 1407

**Comment by Phaiax** [comment]
I forked it. You can merge here:
https://github.com/yawd/yawd-elfinder/pull/17

**Comment by ghost** [comment]
Ok I reproduced this, will merge your fix
