### ISSUE TITLE
ELFINDER_LANGUAGES : next code does not add language file to javascript media.

### ISSUE THREAD

**Issue by kolesnikova-tavi** [ppetrid/yawd-elfinder#18]
for example, I need a file elfinder.ru.js

settings.py
...
ELFINDER_LANGUAGES = ["ru"]

widget.py
...
self.current_locale = to_locale(get_language()) 
# return "ru_RU"
...
if not self.current_locale.startswith('en') and self.current_locale in ls.ELFINDER_LANGUAGES:
# return false

**Comment by ghost** [comment]
yawd-elfinder automatically detects the language based on the current django language. It does not accept an
ELFINDER_LANGUAGES setting. For example, if in your settings.py:

LANGUAGE_CODE = 'ru'

The above would switch both your admin site and elfinder to Russian.
Additionally if you use django internationalization (https://docs.djangoproject.com/en/dev/topics/i18n/translation/), while activating a language yawd-elfinder will automatically switch to that language.

Is this behavior working for you? Do you need to have elfinder show up in a different language than the system language (e.g. admin site in English and elfinder in russian)?

**Comment by kolesnikova-tavi** [comment]
Yes, it's working.
Thank you very much!
