### ISSUE TITLE
Exception when upload file with no ascii filename. (no unicode support)

### ISSUE THREAD

**Issue by pahaz** [ppetrid/yawd-elfinder#20]
ON view, exception in json.parse https://github.com/yawd/yawd-elfinder/blob/master/elfinder/views.py#L50 

```
Exception Type: UnicodeDecodeError at /elfinder/yawd-connector/default/default/
Exception Value: 'utf8' codec can't decode byte 0xcf in position 0: invalid continuation byte
```

On upload, error at volume https://github.com/yawd/yawd-elfinder/blob/master/elfinder/volumes/base.py#L797 , and except on this https://github.com/yawd/yawd-elfinder/blob/master/elfinder/connector.py#L544

```
UnicodeDecodeError 'ascii' codec can't encode characters in position 4-13: ordinal not in range(128)
```

**Comment by ghost** [comment]
I guess this is actually #22?

**Comment by pahaz** [comment]
yes
