### ISSUE TITLE
Elfinder don't work in Inline

### ISSUE THREAD

**Issue by 124bit** [ppetrid/yawd-elfinder#29]
I try to  use elfinder in inline. In my inline model I have only elfinder field. inline extra=0
When I am clicking "Set" it only redirects me at model list page and I see saved model.

Also if inline extra=0 set to 1 all will work fine but on only at first inline. At next dynamically added on page inlines it wouldn't work(

Also there is no label of elfinder field in tabular inline

**Comment by ghost** [comment]
That took a while! The problem stands in django admin application and is described in the following ticket: https://code.djangoproject.com/ticket/15760 . A workaround has been uploaded to fix this issue until the django ticket is closed.
