### ISSUE TITLE
Elfinder settings must be contain only strings.

### ISSUE THREAD

**Issue by pahaz** [ppetrid/yawd-elfinder#31]
Now settings contain variables, that needed import.

```
# from os.path import join
# from elfinder.utils.accesscontrol import fs_standard_access
# from elfinder.volumes.filesystem import ElfinderVolumeLocalFileSystem
```

And if i`m want change them in settings.py you need import them. 

And i`m get error if use import:
`ImproperlyConfigured: The SECRET_KEY setting must not be empty.`

**Comment by ghost** [comment]
The 'driver' option con now be a string (e.g. 'driver': 'elfinder.volumes.filesystem.ElfinderVolumeLocalFileSystem'). As for the accessControl option, importing the fs_standard_access in your settings file shouldn't be a problem. This option is about to be removed in favor of signals anyway - see #9.

Is it ok for you now, or are you still facing problems?

**Comment by pahaz** [comment]
Yes. thanks.

**Comment by FilippoIOVINE** [comment]
Hi,
Maybe I am missing something about this "new" feature but I am getting an
AttributeError: 'str' object has no attribute '_driver_id'
when using this branch.
I know this is quite an old app for django but I really love it and I'd like to know if I did something wrong.
