### ISSUE TITLE
Django 1.5.1

### ISSUE THREAD

**Issue by electrocoder** [ppetrid/yawd-elfinder#33]
Downloading/unpacking Django>=1.4,<1.5 (from yawd-elfinder)
  Downloading Django-1.4.5.tar.gz (7.7MB): 7.7MB downloaded
  Running setup.py egg_info for package Django

  Found existing installation: Django 1.5.1
    Uninstalling Django:

**Comment by ghost** [comment]
Hello, it seems you're using the version from pypi or the 0.90.x branch? 
For Django 1.5 support you must use the github master (we'll update the pypi package soon though)
