### ISSUE TITLE
PIL Requirement

### ISSUE THREAD

**Issue by Xaroth** [ppetrid/yawd-elfinder#34]
Not sure if you've been made aware, but PIL has become deprecated in favour of Pillow (a PIL fork/replacement).

The module should be compatible with PIL, so only the requirements.txt would need an update.

**Comment by ghost** [comment]
Hello, I just merged this pull request https://github.com/yawd/yawd-elfinder/pull/32. I'll also update requirements.txt tomorrow, we use Pillow as well.
