### ISSUE TITLE
elfinder in django 1.6

### ISSUE THREAD

**Issue by CARocha** [ppetrid/yawd-elfinder#38]
Hi, is posible install and configure elfinder with django 1.6.3? when a try install with pip this uninstall version 1.6.3 and install version 1.4.11 django? is posible install and used

Cheers

**Comment by oscarcp** [comment]
You can install it, but it will break (even from the git version), because it is using old templatetags (for example the reverse url tag) wich are different between django 1.4.x to 1.5.x onwards

**Comment by patipatini** [comment]
Hi, thanks for your work on yawd-elfinder. I understood that even the git version doesn't work with django 1.6, so I was wondering if you already knew when it will be available ? I only need a rough hint like _"maybe in few months"_ or _"we're not working on it, don't expect it before years"_.
Thanks

**Comment by oscarcp** [comment]
No clue, I'm not from the dev team, I just found out while trying to use it for a project, but it doesn't seem that they're going to update it soon, since it's based on their company requirements

**Comment by ghost** [comment]
Hello, sorry for the late reaction. I'm afraid updating yawd-elfinder is not currently in our plans, we are a small team (two people) and we're currently tied to a long-running project that does not use yawd-elfinder. Having said that, we will gladly accept / review any contributions to yawd-elfinder and we could also discuss for a new maintainer if anyone's interested!

**Comment by oscarcp** [comment]
I'd happily contribute if I have the time since the update for elfinder to 1.6.x seems to be fairly easy (just some templatetags modifications here and there) but I don't know if you want retrocompatibility with old django versions as well

**Comment by patipatini** [comment]
Thanks for the answers. I'm quite a beginner but I'll have a look at the code too, in order to see if I can make it.

**Comment by ghost** [comment]
I think compatibility with Django <= 1.5 should not be a concern. There have been no significant changes in the yawd-elfinder core the past months; one can just use an older yawd-elfinder version  with Django<=1.5 and the functionality will be more or less the same.

**Comment by CARocha** [comment]
thank all for yours answer!
